graph TD
    092270d(["`
    Commit 092270d:
    Add Maxim author to README.md file.
    Maxim 2024-11-07 11:37:10:
    README.md
    `"])
    406d18d(["`
    Commit 406d18d:
    Create README.md
    Ivan 2024-11-07 11:35:41:
    README.md
    `"])
    092270d --> 406d18d
    01f14b4(["`
    Commit 01f14b4:
    First commit.
    Maxim 2024-11-07 11:33:37:
    No changes
    `"])
    406d18d --> 01f14b4
